openapi: 3.2.0
info:
  title: CoinGecko Pro Nfts API
  version: 3.0.0
servers:
- url: https://pro-api.coingecko.com/api/v3
security:
- headerAuth: []
- queryAuth: []
tags:
- name: Nfts
paths:
  /nfts/list:
    get:
      summary: NFTs List
      description: To query all supported NFTs with ID, contract address, name, asset platform ID and symbol on CoinGecko
      operationId: nfts-list
      x-mint:
        href: /reference/nfts-list
      parameters:
      - name: order
        in: query
        required: false
        description: Sort order of responses.
        schema:
          type: string
          enum:
          - h24_volume_usd_asc
          - h24_volume_usd_desc
          - h24_volume_native_asc
          - h24_volume_native_desc
          - floor_price_native_asc
          - floor_price_native_desc
          - market_cap_native_asc
          - market_cap_native_desc
          - market_cap_usd_asc
          - market_cap_usd_desc
      - name: per_page
        in: query
        required: false
        description: "Total results per page. \nValid values: 1...250"
        schema:
          type: integer
      - name: page
        in: query
        required: false
        description: Page through results.
        schema:
          type: integer
      responses:
        '200':
          description: List of supported NFTs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NFTsList'
              example:
              - id: cryptopunks
                contract_address: '0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB'
                name: CryptoPunks
                asset_platform_id: ethereum
                symbol: PUNK
              - id: bored-ape-yacht-club
                contract_address: '0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d'
                name: Bored Ape Yacht Club
                asset_platform_id: ethereum
                symbol: BAYC
      tags:
      - Nfts
  /nfts/{id}:
    get:
      summary: NFTs Collection Data by ID
      description: To query all the NFT data (name, floor price, 24hr volume, ...) based on the NFT collection ID
      operationId: nfts-id
      x-mint:
        href: /reference/nfts-id
      parameters:
      - name: id
        in: path
        required: true
        description: "NFT collection ID. \n*refers to [`/nfts/list`](/reference/nfts-list)."
        schema:
          type: string
          default: pudgy-penguins
      responses:
        '200':
          description: NFT collection data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NFTData'
              example:
                id: pudgy-penguins
                web_slug: pudgy-penguins
                contract_address: '0xBd3531dA5CF5857e7CfAA92426877b022e612cf8'
                asset_platform_id: ethereum
                name: Pudgy Penguins
                symbol: PPG
                image:
                  small: https://coin-images.coingecko.com/nft_contracts/images/38/small/pudgy.jpg?1730778323
                  small_2x: https://coin-images.coingecko.com/nft_contracts/images/38/small_2x/pudgy.jpg?1730778323
                banner_image: https://coin-images.coingecko.com/nft_contracts/images/38/pudgy-penguins-banner.jpg?1730778702
                description: '<h3>What Is the Pudgy Penguins NFT Collection?</h3>


                  <p>Pudgy Penguins is a collection of 8,888 unique NFTs featuring cute cartoon penguins, which are generated from a collection of 150 different hand-drawn traits.'
                native_currency: ethereum
                native_currency_symbol: ETH
                market_cap_rank: 3
                floor_price:
                  native_currency: 4.67
                  usd: 9713.91
                market_cap:
                  native_currency: 41507
                  usd: 86337207
                volume_24h:
                  native_currency: 28.01
                  usd: 58262
                floor_price_in_usd_24h_percentage_change: -1.78233
                floor_price_24h_percentage_change:
                  usd: -1.782332967792004
                  native_currency: -0.6361858762952403
                market_cap_24h_percentage_change:
                  usd: -1.782332967792065
                  native_currency: -0.6361858762952404
                volume_24h_percentage_change:
                  usd: -41.588610680147845
                  native_currency: -40.90698133583369
                number_of_unique_addresses: 5174.0
                number_of_unique_addresses_24h_percentage_change: -0.01932
                volume_in_usd_24h_percentage_change: -41.58861
                total_supply: 8888.0
                one_day_sales: 6.0
                one_day_sales_24h_percentage_change: -40.0
                one_day_average_sale_price: 4.668316666666667
                one_day_average_sale_price_24h_percentage_change: -1.511635559722812
                links:
                  homepage: https://www.pudgypenguins.com/
                  twitter: https://twitter.com/pudgypenguins
                  discord: https://discord.gg/pudgypenguins
                floor_price_7d_percentage_change:
                  usd: -2.6085983246414655
                  native_currency: -1.1974800093036855
                floor_price_14d_percentage_change:
                  usd: -24.816051386825123
                  native_currency: -16.157991023339317
                floor_price_30d_percentage_change:
                  usd: -20.72768500482924
                  native_currency: -12.366254928188072
                floor_price_60d_percentage_change:
                  usd: 15.176366939745344
                  native_currency: 13.07508549033547
                floor_price_1y_percentage_change:
                  usd: -60.37112564100154
                  native_currency: -51.85567113402062
                explorers:
                - name: Etherscan
                  link: https://etherscan.io/token/0xBd3531dA5CF5857e7CfAA92426877b022e612cf8
                - name: Ethplorer
                  link: https://ethplorer.io/address/0xBd3531dA5CF5857e7CfAA92426877b022e612cf8
                user_favorites_count: 10135
                ath:
                  native_currency: 36.33
                  usd: 145728
                ath_change_percentage:
                  native_currency: -87.1456099642169
                  usd: -93.3388047739623
                ath_date:
                  native_currency: '2024-12-17T07:50:05.897Z'
                  usd: '2024-12-17T08:35:07.390Z'
      tags:
      - Nfts
  /nfts/{asset_platform_id}/contract/{contract_address}:
    get:
      summary: NFTs Collection Data by Contract Address
      description: To query all the NFT data (name, floor price, 24hr volume, ...) based on the NFT collection contract address and respective asset platform
      operationId: nfts-contract-address
      x-mint:
        href: /reference/nfts-contract-address
      parameters:
      - name: asset_platform_id
        in: path
        required: true
        description: "Asset platform ID. \n*refers to [`/asset_platforms`](/reference/asset-platforms-list)."
        schema:
          type: string
          default: ethereum
      - name: contract_address
        in: path
        required: true
        description: Contract address of the NFT collection.
        schema:
          type: string
          default: '0xBd3531dA5CF5857e7CfAA92426877b022e612cf8'
      responses:
        '200':
          description: NFT collection data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NFTData'
              example:
                id: pudgy-penguins
                web_slug: pudgy-penguins
                contract_address: '0xBd3531dA5CF5857e7CfAA92426877b022e612cf8'
                asset_platform_id: ethereum
                name: Pudgy Penguins
                symbol: PPG
                image:
                  small: https://coin-images.coingecko.com/nft_contracts/images/38/small/pudgy.jpg?1730778323
                  small_2x: https://coin-images.coingecko.com/nft_contracts/images/38/small_2x/pudgy.jpg?1730778323
                banner_image: https://coin-images.coingecko.com/nft_contracts/images/38/pudgy-penguins-banner.jpg?1730778702
                description: '<h3>What Is the Pudgy Penguins NFT Collection?</h3>


                  <p>Pudgy Penguins is a collection of 8,888 unique NFTs featuring cute cartoon penguins, which are generated from a collection of 150 different hand-drawn traits.'
                native_currency: ethereum
                native_currency_symbol: ETH
                market_cap_rank: 3
                floor_price:
                  native_currency: 4.67
                  usd: 9708.85
                market_cap:
                  native_currency: 41507
                  usd: 86292262
                volume_24h:
                  native_currency: 28.01
                  usd: 58232
                floor_price_in_usd_24h_percentage_change: -1.78233
                floor_price_24h_percentage_change:
                  usd: -1.782332967792004
                  native_currency: -0.6361858762952403
                market_cap_24h_percentage_change:
                  usd: -1.782332967792065
                  native_currency: -0.6361858762952404
                volume_24h_percentage_change:
                  usd: -41.588610680147845
                  native_currency: -40.90698133583369
                number_of_unique_addresses: 5174.0
                number_of_unique_addresses_24h_percentage_change: -0.01932
                volume_in_usd_24h_percentage_change: -41.58861
                total_supply: 8888.0
                one_day_sales: 6.0
                one_day_sales_24h_percentage_change: -40.0
                one_day_average_sale_price: 4.668316666666667
                one_day_average_sale_price_24h_percentage_change: -1.511635559722812
                links:
                  homepage: https://www.pudgypenguins.com/
                  twitter: https://twitter.com/pudgypenguins
                  discord: https://discord.gg/pudgypenguins
                floor_price_7d_percentage_change:
                  usd: -2.6085983246414655
                  native_currency: -1.1974800093036855
                floor_price_14d_percentage_change:
                  usd: -24.816051386825123
                  native_currency: -16.157991023339317
                floor_price_30d_percentage_change:
                  usd: -20.72768500482924
                  native_currency: -12.366254928188072
                floor_price_60d_percentage_change:
                  usd: 15.176366939745344
                  native_currency: 13.07508549033547
                floor_price_1y_percentage_change:
                  usd: -60.37112564100154
                  native_currency: -51.85567113402062
                explorers:
                - name: Etherscan
                  link: https://etherscan.io/token/0xBd3531dA5CF5857e7CfAA92426877b022e612cf8
                - name: Ethplorer
                  link: https://ethplorer.io/address/0xBd3531dA5CF5857e7CfAA92426877b022e612cf8
                user_favorites_count: 10135
                ath:
                  native_currency: 36.33
                  usd: 145728
                ath_change_percentage:
                  native_currency: -87.1456099642169
                  usd: -93.3388047739623
                ath_date:
                  native_currency: '2024-12-17T07:50:05.897Z'
                  usd: '2024-12-17T08:35:07.390Z'
      tags:
      - Nfts
  /nfts/markets:
    get:
      summary: NFTs List with Market Data
      description: To query all the supported NFT collections with floor price, market cap, volume and market related data on CoinGecko
      operationId: nfts-markets
      x-mint:
        href: /reference/nfts-markets
      parameters:
      - name: asset_platform_id
        in: query
        required: false
        description: "Filter result by asset platform (blockchain network). \n*refers to [`/asset_platforms`](/reference/asset-platforms-list) filter=`nft`."
        schema:
          type: string
      - name: order
        in: query
        required: false
        description: "Sort results by field. \nDefault: `market_cap_usd_desc`"
        schema:
          type: string
          enum:
          - h24_volume_native_asc
          - h24_volume_native_desc
          - h24_volume_usd_asc
          - h24_volume_usd_desc
          - market_cap_usd_asc
          - market_cap_usd_desc
      - name: per_page
        in: query
        required: false
        description: "Total results per page. \nDefault value: 100 \nValid values: 1...250"
        schema:
          type: integer
      - name: page
        in: query
        required: false
        description: "Page through results. \nDefault value: 1"
        schema:
          type: integer
      responses:
        '200':
          description: List of NFT collections with market data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NFTsMarkets'
              example:
              - id: cryptopunks
                contract_address: '0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB'
                asset_platform_id: ethereum
                name: CryptoPunks
                symbol: PUNK
                image:
                  small: https://coin-images.coingecko.com/nft_contracts/images/270/small/cryptopunks.png?1707287245
                  small_2x: https://coin-images.coingecko.com/nft_contracts/images/270/small_2x/cryptopunks.png?1707287245
                description: '<h3 dir="ltr">What Is the CryptoPunks NFT Collection?</h3>


                  <p dir="ltr">CryptoPunks is an Ethereum-based NFT collection of 10,000 unique art characters.'
                native_currency: ethereum
                native_currency_symbol: ETH
                floor_price:
                  native_currency: 32.99
                  usd: 68598
                market_cap:
                  native_currency: 329702
                  usd: 685567614
                volume_24h:
                  native_currency: 0.0
                  usd: 0.0
                floor_price_in_usd_24h_percentage_change: -2.61445
                floor_price_24h_percentage_change:
                  usd: -2.614447557256636
                  native_currency: -0.7222389407162203
                market_cap_24h_percentage_change:
                  usd: -2.6144475572566117
                  native_currency: -0.7222389407162202
                volume_24h_percentage_change:
                  usd: -100.0
                  native_currency: -100.0
                number_of_unique_addresses: 100.0
                number_of_unique_addresses_24h_percentage_change: 0.0
                volume_in_usd_24h_percentage_change: -100.0
                total_supply: 9994.0
                one_day_sales: null
                one_day_sales_24h_percentage_change: 0.0
                one_day_average_sale_price: null
                one_day_average_sale_price_24h_percentage_change: 0.0
              - id: bored-ape-yacht-club
                contract_address: '0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d'
                asset_platform_id: ethereum
                name: Bored Ape Yacht Club
                symbol: BAYC
                image:
                  small: https://coin-images.coingecko.com/nft_contracts/images/20/small/bored-ape-yacht-club.png?1707287177
                  small_2x: https://coin-images.coingecko.com/nft_contracts/images/20/small_2x/bored-ape-yacht-club.png?1707287177
                description: '<h3>What Is the Bored Ape Yacht Club NFT Collection?</h3>


                  <p>The Bored Ape Yacht Club is a collection of 10,000 unique Bored Ape NFTs, which showcase a series of apes with different characteristics and expressions.'
                native_currency: ethereum
                native_currency_symbol: ETH
                floor_price:
                  native_currency: 8.69
                  usd: 18036.28
                market_cap:
                  native_currency: 86883
                  usd: 180326699
                volume_24h:
                  native_currency: 166.12
                  usd: 344783
                floor_price_in_usd_24h_percentage_change: -4.33779
                floor_price_24h_percentage_change:
                  usd: -4.33779438865101
                  native_currency: -1.7857142857131758
                market_cap_24h_percentage_change:
                  usd: -4.337794388651022
                  native_currency: -1.7857142857131754
                volume_24h_percentage_change:
                  usd: 10.090203438665934
                  native_currency: 27.149001523165122
                number_of_unique_addresses: 5653.0
                number_of_unique_addresses_24h_percentage_change: -0.05304
                volume_in_usd_24h_percentage_change: 10.0902
                total_supply: 9998.0
                one_day_sales: 18.0
                one_day_sales_24h_percentage_change: 50.0
                one_day_average_sale_price: 9.228827722222222
                one_day_average_sale_price_24h_percentage_change: -15.23399898455658
      tags:
      - Nfts
  /nfts/{id}/market_chart:
    get:
      summary: NFTs Collection Historical Chart Data by ID
      description: To query historical market data of a NFT collection, including floor price, market cap, and 24hr volume, by number of days away from now
      operationId: nfts-id-market-chart
      x-mint:
        href: /reference/nfts-id-market-chart
      parameters:
      - name: id
        in: path
        required: true
        description: "NFT collection ID. \n*refers to [`/nfts/list`](/reference/nfts-list)."
        schema:
          type: string
          default: pudgy-penguins
      - name: days
        in: query
        required: true
        description: "Data up to number of days ago. \nValid values: any integer or `max`"
        schema:
          type: string
          default: '1'
      responses:
        '200':
          description: NFT collection historical chart data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NFTMarketChart'
              example:
                floor_price_usd:
                - - 1779729001000
                  - 10032.419904380335
                - - 1779729303000
                  - 10028.703755252538
                floor_price_native:
                - - 1779729001000
                  - 4.69989940999941
                - - 1779729303000
                  - 4.69989940999941
                h24_volume_usd:
                - - 1779729001000
                  - 60835.49928667799
                - - 1779729303000
                  - 60812.96496397539
                h24_volume_native:
                - - 1779729001000
                  - 28.49967703999703
                - - 1779729303000
                  - 28.49967703999703
                market_cap_usd:
                - - 1779729001000
                  - 89168148.1101324
                - - 1779729303000
                  - 89135118.97668457
                market_cap_native:
                - - 1779729001000
                  - 41772.70595607475
                - - 1779729303000
                  - 41772.70595607475
      tags:
      - Nfts
  /nfts/{asset_platform_id}/contract/{contract_address}/market_chart:
    get:
      summary: NFTs Collection Historical Chart Data by Contract Address
      description: To query historical market data of a NFT collection, including floor price, market cap, and 24hr volume, by number of days away from now based on the provided contract address
      operationId: nfts-contract-address-market-chart
      x-mint:
        href: /reference/nfts-contract-address-market-chart
      parameters:
      - name: asset_platform_id
        in: path
        required: true
        description: "Asset platform ID. \n*refers to [`/asset_platforms`](/reference/asset-platforms-list)."
        schema:
          type: string
          default: ethereum
      - name: contract_address
        in: path
        required: true
        description: Contract address of the NFT collection.
        schema:
          type: string
          default: '0xBd3531dA5CF5857e7CfAA92426877b022e612cf8'
      - name: days
        in: query
        required: true
        description: "Data up to number of days ago. \nValid values: any integer or `max`"
        schema:
          type: string
          default: '1'
      responses:
        '200':
          description: NFT collection historical chart data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NFTMarketChart'
              example:
                floor_price_usd:
                - - 1779729001000
                  - 10032.419904380335
                - - 1779729303000
                  - 10028.703755252538
                floor_price_native:
                - - 1779729001000
                  - 4.69989940999941
                - - 1779729303000
                  - 4.69989940999941
                h24_volume_usd:
                - - 1779729001000
                  - 60835.49928667799
                - - 1779729303000
                  - 60812.96496397539
                h24_volume_native:
                - - 1779729001000
                  - 28.49967703999703
                - - 1779729303000
                  - 28.49967703999703
                market_cap_usd:
                - - 1779729001000
                  - 89168148.1101324
                - - 1779729303000
                  - 89135118.97668457
                market_cap_native:
                - - 1779729001000
                  - 41772.70595607475
                - - 1779729303000
                  - 41772.70595607475
      tags:
      - Nfts
  /nfts/{id}/tickers:
    get:
      summary: NFTs Collection Tickers by ID
      description: To query the latest floor price and 24hr volume of a NFT collection, on each NFT marketplace, e.g. OpenSea and Blur
      operationId: nfts-id-tickers
      x-mint:
        href: /reference/nfts-id-tickers
      parameters:
      - name: id
        in: path
        required: true
        description: "NFT collection ID. \n*refers to [`/nfts/list`](/reference/nfts-list)."
        schema:
          type: string
          default: pudgy-penguins
      responses:
        '200':
          description: NFT collection tickers data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NFTTickers'
              example:
                tickers:
                - floor_price_in_native_currency: 5.57
                  h24_volume_in_native_currency: 4.56
                  native_currency: ethereum
                  native_currency_symbol: ETH
                  updated_at: '2026-05-26T17:00:49.982Z'
                  nft_marketplace_id: opensea
                  name: OpenSea
                  image: https://coin-images.coingecko.com/nft_marketplaces/images/1/small/Opensea.png?1686193426
                  nft_collection_url: https://opensea.io/collection/pudgypenguins
                - floor_price_in_native_currency: 4.67
                  h24_volume_in_native_currency: 28.12
                  native_currency: ethereum
                  native_currency_symbol: ETH
                  updated_at: '2026-05-26T17:00:49.862Z'
                  nft_marketplace_id: blur
                  name: Blur
                  image: https://coin-images.coingecko.com/nft_marketplaces/images/20/small/blur_logo.jpg?1690993708
                  nft_collection_url: https://blur.io/collection/pudgypenguins
      tags:
      - Nfts
components:
  schemas:
    NFTsList:
      type: array
      items:
        type: object
        required:
        - id
        - contract_address
        - name
        - asset_platform_id
        - symbol
        properties:
          id:
            type: string
            description: NFT collection ID
          contract_address:
            type: string
            description: NFT collection contract address
          name:
            type: string
            description: NFT collection name
          asset_platform_id:
            type: string
            description: NFT collection asset platform ID
          symbol:
            type: string
            description: NFT collection symbol
    NFTData:
      type: object
      required:
      - id
      - web_slug
      - contract_address
      - asset_platform_id
      - name
      - symbol
      - image
      - banner_image
      - description
      - native_currency
      - native_currency_symbol
      - market_cap_rank
      - floor_price
      - market_cap
      - volume_24h
      - floor_price_in_usd_24h_percentage_change
      - floor_price_24h_percentage_change
      - market_cap_24h_percentage_change
      - volume_24h_percentage_change
      - number_of_unique_addresses
      - number_of_unique_addresses_24h_percentage_change
      - volume_in_usd_24h_percentage_change
      - total_supply
      - one_day_sales
      - one_day_sales_24h_percentage_change
      - one_day_average_sale_price
      - one_day_average_sale_price_24h_percentage_change
      - links
      - floor_price_7d_percentage_change
      - floor_price_14d_percentage_change
      - floor_price_30d_percentage_change
      - floor_price_60d_percentage_change
      - floor_price_1y_percentage_change
      - explorers
      - user_favorites_count
      - ath
      - ath_change_percentage
      - ath_date
      properties:
        id:
          type: string
          description: NFT collection ID
        web_slug:
          type: string
          description: NFT collection web slug
        contract_address:
          type: string
          description: NFT collection contract address
        asset_platform_id:
          type: string
          description: NFT collection asset platform ID
        name:
          type: string
          description: NFT collection name
        symbol:
          type: string
          description: NFT collection symbol
        image:
          type: object
          description: NFT collection image URLs
          properties:
            small:
              type: string
            small_2x:
              type: string
        banner_image:
          type: string
          description: NFT collection banner image URL
        description:
          type: string
          description: NFT collection description
        native_currency:
          type: string
          description: NFT collection native currency
        native_currency_symbol:
          type: string
          description: NFT collection native currency symbol
        market_cap_rank:
          type:
          - integer
          - 'null'
          description: NFT collection market cap rank
        floor_price:
          type: object
          description: NFT collection floor price
          properties:
            native_currency:
              type: number
            usd:
              type: number
        market_cap:
          type: object
          description: NFT collection market cap
          properties:
            native_currency:
              type: number
            usd:
              type: number
        volume_24h:
          type: object
          description: NFT collection volume in 24 hours
          properties:
            native_currency:
              type: number
            usd:
              type: number
        floor_price_in_usd_24h_percentage_change:
          type: number
          description: NFT collection floor price in USD 24 hours percentage change
        floor_price_24h_percentage_change:
          type: object
          description: NFT collection floor price 24 hours percentage change
          properties:
            usd:
              type: number
            native_currency:
              type: number
        market_cap_24h_percentage_change:
          type: object
          description: NFT collection market cap 24 hours percentage change
          properties:
            usd:
              type: number
            native_currency:
              type: number
        volume_24h_percentage_change:
          type: object
          description: NFT collection volume in 24 hours percentage change
          properties:
            usd:
              type: number
            native_currency:
              type: number
        number_of_unique_addresses:
          type: number
          description: Number of unique addresses owning the NFTs
        number_of_unique_addresses_24h_percentage_change:
          type: number
          description: Number of unique addresses 24 hours percentage change
        volume_in_usd_24h_percentage_change:
          type: number
          description: NFT collection volume in USD 24 hours percentage change
        total_supply:
          type: number
          description: NFT collection total supply
        one_day_sales:
          type:
          - number
          - 'null'
          description: NFT collection one day sales
        one_day_sales_24h_percentage_change:
          type: number
          description: NFT collection one day sales 24 hours percentage change
        one_day_average_sale_price:
          type:
          - number
          - 'null'
          description: NFT collection one day average sale price
        one_day_average_sale_price_24h_percentage_change:
          type: number
          description: NFT collection one day average sale price 24 hours percentage change
        links:
          type: object
          description: NFT collection links
          properties:
            homepage:
              type: string
            twitter:
              type: string
            discord:
              type: string
        floor_price_7d_percentage_change:
          type: object
          description: NFT collection floor price 7 days percentage change
          properties:
            usd:
              type: number
            native_currency:
              type: number
        floor_price_14d_percentage_change:
          type: object
          description: NFT collection floor price 14 days percentage change
          properties:
            usd:
              type: number
            native_currency:
              type: number
        floor_price_30d_percentage_change:
          type: object
          description: NFT collection floor price 30 days percentage change
          properties:
            usd:
              type: number
            native_currency:
              type: number
        floor_price_60d_percentage_change:
          type: object
          description: NFT collection floor price 60 days percentage change
          properties:
            usd:
              type: number
            native_currency:
              type: number
        floor_price_1y_percentage_change:
          type: object
          description: NFT collection floor price 1 year percentage change
          properties:
            usd:
              type: number
            native_currency:
              type: number
        explorers:
          type: array
          description: NFT collection block explorer links
          items:
            type: object
            properties:
              name:
                type: string
              link:
                type: string
        user_favorites_count:
          type: integer
          description: NFT collection user favorites count
        ath:
          type: object
          description: NFT collection all time highs
          properties:
            native_currency:
              type: number
            usd:
              type: number
        ath_change_percentage:
          type: object
          description: NFT collection all time highs change percentage
          properties:
            native_currency:
              type: number
            usd:
              type: number
        ath_date:
          type: object
          description: NFT collection all time highs date
          properties:
            native_currency:
              type: string
              format: date-time
            usd:
              type: string
              format: date-time
    NFTsMarkets:
      type: array
      items:
        type: object
        required:
        - id
        - contract_address
        - asset_platform_id
        - name
        - symbol
        - image
        - description
        - native_currency
        - native_currency_symbol
        - floor_price
        - market_cap
        - volume_24h
        - floor_price_in_usd_24h_percentage_change
        - floor_price_24h_percentage_change
        - market_cap_24h_percentage_change
        - volume_24h_percentage_change
        - number_of_unique_addresses
        - number_of_unique_addresses_24h_percentage_change
        - volume_in_usd_24h_percentage_change
        - total_supply
        - one_day_sales
        - one_day_sales_24h_percentage_change
        - one_day_average_sale_price
        - one_day_average_sale_price_24h_percentage_change
        properties:
          id:
            type: string
            description: NFT collection ID
          contract_address:
            type:
            - string
            - 'null'
            description: NFT collection contract address
          asset_platform_id:
            type: string
            description: NFT collection asset platform ID
          name:
            type: string
            description: NFT collection name
          symbol:
            type: string
            description: NFT collection symbol
          image:
            type: object
            description: NFT collection image URLs
            properties:
              small:
                type: string
              small_2x:
                type: string
          description:
            type:
            - string
            - 'null'
            description: NFT collection description
          native_currency:
            type: string
            description: NFT collection native currency
          native_currency_symbol:
            type: string
            description: NFT collection native currency symbol
          floor_price:
            type: object
            description: NFT collection floor price
            properties:
              native_currency:
                type: number
              usd:
                type: number
          market_cap:
            type: object
            description: NFT collection market cap
            properties:
              native_currency:
                type: number
              usd:
                type: number
          volume_24h:
            type: object
            description: NFT collection volume in 24 hours
            properties:
              native_currency:
                type: number
              usd:
                type: number
          floor_price_in_usd_24h_percentage_change:
            type: number
            description: NFT collection floor price in USD 24 hours percentage change
          floor_price_24h_percentage_change:
            type: object
            description: NFT collection floor price 24 hours percentage change
            properties:
              usd:
                type: number
              native_currency:
                type: number
          market_cap_24h_percentage_change:
            type: object
            description: NFT collection market cap 24 hours percentage change
            properties:
              usd:
                type: number
              native_currency:
                type: number
          volume_24h_percentage_change:
            type: object
            description: NFT collection volume in 24 hours percentage change
            properties:
              usd:
                type: number
              native_currency:
                type: number
          number_of_unique_addresses:
            type:
            - number
            - 'null'
            description: Number of unique addresses owning the NFTs
          number_of_unique_addresses_24h_percentage_change:
            type: number
            description: Number of unique addresses 24 hours percentage change
          volume_in_usd_24h_percentage_change:
            type: number
            description: NFT collection volume in USD 24 hours percentage change
          total_supply:
            type:
            - number
            - 'null'
            description: NFT collection total supply
          one_day_sales:
            type:
            - number
            - 'null'
            description: NFT collection one day sales
          one_day_sales_24h_percentage_change:
            type: number
            description: NFT collection one day sales 24 hours percentage change
          one_day_average_sale_price:
            type:
            - number
            - 'null'
            description: NFT collection one day average sale price
          one_day_average_sale_price_24h_percentage_change:
            type: number
            description: NFT collection one day average sale price 24 hours percentage change
    NFTMarketChart:
      type: object
      required:
      - floor_price_usd
      - floor_price_native
      - h24_volume_usd
      - h24_volume_native
      - market_cap_usd
      - market_cap_native
      properties:
        floor_price_usd:
          type: array
          description: NFT collection floor price in USD as [timestamp, price] pairs
          items:
            type: array
            items:
              type: number
        floor_price_native:
          type: array
          description: NFT collection floor price in native currency as [timestamp, price] pairs
          items:
            type: array
            items:
              type: number
        h24_volume_usd:
          type: array
          description: NFT collection 24h volume in USD as [timestamp, volume] pairs
          items:
            type: array
            items:
              type: number
        h24_volume_native:
          type: array
          description: NFT collection 24h volume in native currency as [timestamp, volume] pairs
          items:
            type: array
            items:
              type: number
        market_cap_usd:
          type: array
          description: NFT collection market cap in USD as [timestamp, market_cap] pairs
          items:
            type: array
            items:
              type: number
        market_cap_native:
          type: array
          description: NFT collection market cap in native currency as [timestamp, market_cap] pairs
          items:
            type: array
            items:
              type: number
    NFTTickers:
      type: object
      required:
      - tickers
      properties:
        tickers:
          type: array
          items:
            type: object
            required:
            - floor_price_in_native_currency
            - h24_volume_in_native_currency
            - native_currency
            - native_currency_symbol
            - updated_at
            - nft_marketplace_id
            - name
            - image
            - nft_collection_url
            properties:
              floor_price_in_native_currency:
                type: number
                description: NFT collection floor price in native currency
              h24_volume_in_native_currency:
                type: number
                description: NFT collection volume in 24 hours in native currency
              native_currency:
                type: string
                description: NFT collection native currency
              native_currency_symbol:
                type: string
                description: NFT collection native currency symbol
              updated_at:
                type: string
                description: Last updated time
              nft_marketplace_id:
                type: string
                description: NFT marketplace ID
              name:
                type: string
                description: NFT marketplace name
              image:
                type: string
                description: NFT marketplace image URL
              nft_collection_url:
                type: string
                description: NFT collection URL in the NFT marketplace
  securitySchemes:
    headerAuth:
      type: apiKey
      in: header
      name: x-cg-pro-api-key
      description: Learn how to [set up your API key](https://docs.coingecko.com/docs/setting-up-your-api-key)
    queryAuth:
      type: apiKey
      in: query
      name: x_cg_pro_api_key
      description: Learn how to [set up your API key](https://docs.coingecko.com/docs/setting-up-your-api-key)
x-provenance:
  method: harvested
  publisher: CoinGecko
  source: https://docs.coingecko.com/openapi-specs/pro-api.json
  note: split by refine-openapis from the provider's own published document, verified by fetch (openapi/_original/*.fetch.json);
    stamped by stamp-openapi-provenance.py (roadmap#793)
